Repository priceline/design-system, pull requests merged in 2020-07, with the labels that each got.

#873 Remove types field from core package to avoid breaking TSC builds
  packages/core/package.json
Labels: bug, typescript

#883 Combine actions for static storybook and docsite
  .github/workflows/build-docs.yml
  .github/workflows/continuous-integration.yml
  .travis.yml
  README.md
  docs/README.md
  docs/package-lock.json
  packages/core/.npmignore
  packages/core/README.md
Labels: maintenance, workflow

#887 Remove unused variables
  codemods/icons-v2-to-v3/iconsV2toV3.js
Labels: bug

#891 Change how we detect Styled Components version
  .gitignore
  package-lock.json
  packages/core/package.json
  packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.js
  packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc3.spec.js
  packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc4.spec.js
Labels: core

#888 Update Slider.stories.js for a11y violations
  packages/slider/storybook/Slider.stories.js
Labels: accessibility, slider

#893 Add note about ThemeProvider to subpackage readmes
  packages/autocomplete/README.md
  packages/icons/README.md
  packages/modal/README.md
  packages/popover/README.md
  packages/slider/README.md
Labels: docs

#894 Update Label default color to text.light
  packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
  packages/core/src/Label/Label.js
  packages/core/src/Label/__snapshots__/Label.spec.js.snap
Labels: bug
