Repository priceline/design-system, pull requests merged in 2020-06, with the labels that each got.

#819 feat(input-prop-types): Add type defs for input related components
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#841 Typescript bugfixes
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
  packages/types/types/tsconfig.json
Labels: typescript

#844 Add boxShadowSize prop to Box
  packages/core/src/Box/Box.js
  packages/core/src/Box/Box.spec.js
  packages/core/src/Box/Box.stories.js
  packages/core/src/Box/__snapshots__/Box.spec.js.snap
  packages/core/src/Card/Card.js
  packages/core/src/Card/__snapshots__/Card.spec.js.snap
  packages/core/src/utils/boxShadow.js
  packages/core/src/utils/index.js
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: core, enhancement

#847 Fix duplicate box-shadow in Card
  packages/core/src/Card/Card.js
  packages/core/src/Card/__snapshots__/Card.spec.js.snap
Labels: bug, v3.5.0

#850 Version bump for 3.5 and updating lockfile
  package-lock.json
  packages/core/package.json
Labels: core, v3.5.0

#853 Add HTML prop types to some components' declarations
  packages/core/package.json
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: bug, typescript

#854 Remove URLs for internal NPM registry
  package-lock.json
  packages/core/package.json
  packages/modal/package.json
Labels: bug

#857 Add README to core project
  packages/core/README.md
Labels: core

#863 Use GH Actions to build docsite and static storybook
  .github/workflows/build-docs.yml
Labels: developer experience, workflow
