Repository priceline/design-system, pull requests merged in 2020-05, with the labels that each got.

#763 Bump core to 3.4.0
  packages/core/package.json
Labels: core

#769 Fix ref prop type ssr
  packages/core/package.json
  packages/core/src/utils.js
Labels: bug, core

#771 fix(721): Remove hardcoded popover theme
  packages/popover/src/Arrow.js
  packages/popover/src/Popover.js
  packages/popover/src/PopoverContent.js
  packages/popover/storybook/Popover.js
  packages/popover/test/__snapshots__/Popover.js.snap
Labels: popover

#775 Bump popover to 3.3.1
  packages/popover/package.json
Labels: popover, version

#804 Fix sc migration utility test
  packages/core/package.json
  packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc3.spec.js
  packages/core/src/utils/getSCMigrationRef/getSCMigrationRef.sc4.spec.js
Labels: may-2020-hackathon

#772 Create package for type declarations
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  packages/core/package.json
  packages/types/README.md
  packages/types/package.json
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
  packages/types/types/tsconfig.json
  packages/types/types/tslint.json
Labels: typescript

#803 Update .travis.yml
  .travis.yml
Labels: may-2020-hackathon

#802 Resolve Lerna warnings
  docs/package.json
  package-lock.json
  package.json
  packages/autocomplete/package.json
  packages/core/package.json
  packages/icons/package.json
  packages/modal/package.json
  packages/popover/package.json
  packages/slider/package.json
  plop-templates/package/package.json.hbs
Labels: may-2020-hackathon

#805 Enable types for core project
  packages/core/package.json
Labels: typescript

#801 Create continuous-integration.yml
  .github/workflows/continuous-integration.yml
Labels: may-2020-hackathon

#807 Use version of @types to match styled-system
  package-lock.json
  packages/core/package.json
  packages/types/package.json
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#808 Update plop template to use new folder structure
  plop-templates/core/index.js.hbs
  plop-templates/core/{{componentName}}.js.hbs
  plop-templates/core/{{componentName}}.spec.js.hbs
  plop-templates/core/{{componentName}}.stories.js.hbs
  plopfile.js
Labels: may-2020-hackathon

#810 Fix Storybook configuration and sub-package stories
  .storybook/addons.js
  .storybook/main.js
  .storybook/presets.js
  .storybook/preview.js
  packages/autocomplete/storybook/Autocomplete.stories.js
  packages/modal/storybook/Modal.stories.js
  packages/popover/storybook/Popover.stories.js
  packages/slider/src/rc-slider/Range.js
  packages/slider/src/rc-slider/Slider.js
  packages/slider/storybook/Slider.stories.js
Labels: developer experience, may-2020-hackathon, storybook

#811 Fix a few LGTM alerts (unused imports)
  packages/modal/src/SmallModalHeader.js
  packages/slider/src/RangeSlider.js
  packages/slider/src/Slider.js
Labels: lgtm, may-2020-hackathon

#812 Add prop types for link, typography, and a11y components
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#816 Add aria-label / aria-lablledby props to Modal
  docs/pages/Modal.md
  packages/modal/README.md
  packages/modal/package.json
  packages/modal/src/Modal.js
  packages/modal/storybook/Modal.stories.js
  packages/modal/test/Modal.js
Labels: may-2020-hackathon

#814 Upgrade to styled-system@^4
  package-lock.json
  packages/autocomplete/package.json
  packages/core/package.json
  packages/core/src/Absolute/Absolute.spec.js
  packages/core/src/Absolute/__snapshots__/Absolute.spec.js.snap
  packages/core/src/Avatar/__snapshots__/Avatar.spec.js.snap
  packages/core/src/Badge/__snapshots__/Badge.spec.js.snap
  packages/core/src/Banner/Banner.stories.js
  packages/core/src/BlockLink/BlockLink.stories.js
  packages/core/src/Card/Card.spec.js
  packages/core/src/Card/__snapshots__/Card.spec.js.snap
  packages/core/src/Divider/__snapshots__/Divider.spec.js.snap
  packages/core/src/Flag/__snapshots__/Flag.spec.js.snap
  packages/core/src/FormField/__snapshots__/FormField.spec.js.snap
  packages/core/src/Relative/Relative.spec.js
  packages/core/src/Relative/__snapshots__/Relative.spec.js.snap
  packages/core/src/Select/__snapshots__/Select.spec.js.snap
  packages/core/src/Stamp/__snapshots__/Stamp.spec.js.snap
  packages/core/src/ToggleBadge/__snapshots__/ToggleBadge.spec.js.snap
  packages/core/src/Tooltip/__snapshots__/Tooltip.spec.js.snap
  packages/icons/package.json
  packages/modal/package.json
  packages/slider/package.json
  packages/types/package.json
Labels: dependencies, may-2020-hackathon

#815 Add prop types for image components
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#817 add custom padding to flag (#259)
  packages/core/src/Flag/Flag.js
  packages/core/src/Flag/Flag.stories.js
Labels: may-2020-hackathon

#820 Add types to exported utility functions
  packages/types/package.json
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#818 Define prop types for icon & buttons
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#822 Add types for Breadcrumbs and Stepper
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#827 Fix package vulnerabilities in the next.js docsite
  README.md
  docs/package-lock.json
  docs/package.json
  docs/src/NavLink.js
  docs/src/SideNav.js
  docs/src/components.js
  docs/src/navigation.js
Labels: may-2020-hackathon

#826 Add Priceline logo to theme
  .storybook/manager.js
  .storybook/pclnTheme.js
Labels: may-2020-hackathon

#824 Fix style bug on popover docs page by disabling stories slot
  packages/popover/storybook/Popover.stories.js
Labels: bug, may-2020-hackathon

#829 Add prop types for badge components
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#831 Add deprecated props to components that already have declarations
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript

#823 Add prop types for static display components
  packages/core/src/Banner/Banner.js
  packages/types/types/index.d.ts
  packages/types/types/test.tsx
Labels: may-2020-hackathon, typescript
