Repository priceline/design-system, pull requests merged in 2020-09, with the labels that each got.

#924 Add v4 announcement and migration guide
  ANNOUNCING_V4.md
  MIGRATION_GUIDES/MIGRATING_to_v2.md
  MIGRATION_GUIDES/MIGRATING_to_v3.md
  MIGRATION_GUIDES/MIGRATING_to_v4.md
Labels: docs

#926 issue(913): Add runtime deprecation for unnamed Icon
  packages/icons/src/Icon.js
Labels: icons

#928 Fix style bug when styling Button
  common/changes/pcln-design-system/fix-styled-button_2020-09-18-18-16.json
  packages/core/src/Button/Button.js
  packages/core/src/Button/Button.spec.js
  packages/core/src/Button/Button.stories.js
Labels: bug
